### ISSUE TITLE
Todos for Ylva 

### ISSUE THREAD

**Issue by IlanIwumbwe** [IlanIwumbwe/Ylva#2]
## Technical enhancements:
- [ ] Debug and improve move ordering and other optimisations to reduce nodes searched during minimax search
- [ ] Taper PSQT evaluation
- [ ] Phase out ray usage

**Comment by IlanIwumbwe** [comment]
## Other enhancements:
- [ ] Add time control
- [ ] Add colour choice for player v engine mode, and ability to change board perspective based on that
- [ ] Add upper bound for engine thinking time. Once this is reached, instead of terminating the search, we fall back on previous iteration best move from full search got from iterative deepening

**Comment by tissatussa** [comment]
Today i used ChatGPT to know more about compiling C / C++ code. This AI was a great help, i saved the page : [ChatGPT-about-compiling-C-C++-code.zip](https://github.com/user-attachments/files/15749535/ChatGPT-about-compiling-C-C%2B%2B-code.zip)

It might interest you.

**Comment by tissatussa** [comment]
how's the UCI implementation going ?

**Comment by IlanIwumbwe** [comment]
> Today i used ChatGPT to know more about compiling C / C++ code. This AI was a great help, i saved the page : [ChatGPT-about-compiling-C-C++-code.zip](https://github.com/user-attachments/files/15749535/ChatGPT-about-compiling-C-C%2B%2B-code.zip)
> 
> It might interest you.

Definitely very interesting, and useful for Ylva and future projects. Thanks! 

> how's the UCI implementation going ?

In truth, I haven't worked on Ylva in the 3 weeks since my last commit due to university coursework and other projects. However, I believe I understand how it works, I just need to make time to work on it soon.

**Comment by tissatussa** [comment]
> Definitely very interesting, and useful for Ylva and future projects...

Yesterday and today i'm exploring GPT more and more. It's a great help for programming, if you never tried it, you certainly should .. and it's free, unlimited ! I discovered a lot of its possibilities today and (very) quicky it gave me lots of useful info. It's important to accurately define your questions by a clear description. I ZIPped that conversation, but there's no need : it's possible to share any conversations (also 'archived' ones) by an URL, which makes them visible - but readonly. Regarding this, i want to share my most recent session with you : [MakeFile tech](https://chatgpt.com/share/8cfc7b7d-2f66-4793-85ec-f20a91754969) you'll be amazed what's possible with Makefile scripting ! (near the end this conversation goes into other subjects, somewhat personal, but that's OK with me). This info about Makefile scripting can also be very helpful for you and it's a good read. I'm happy to share it.

> ..I believe I understand how it works..

The UCI protocol is nice and not hard to understand. And there's a lot of info about it, you'll manage ..

**Comment by tissatussa** [comment]
btw. in the meantime GPT helped me solve all issues regarding that code repair of the Zorgus v1.2.0 engine : compiling is now without any warnings ! This way i learned a lot about C and C++ ! It's really awesome -- i keep repeating :-)

**Comment by tissatussa** [comment]
Here is more nice and valuable info regarding chess engine programming : 

[chess engines : Design decisions & Search techniques & Evaluation](http://www.eglebbk.dds.nl/program/chess-index.html)

[2 threads ?](https://github.com/Orbital-Web/Raphael/issues/1)

[qReverse : an architecture-accelerated array reversal algorithm](https://github.com/Wunkolo/qreverse/blob/master/README.md)

The first link is the homepage of the author of some old engines, he wrote 3 articles which are a good read (see menu).
The second link is about using (2) threads for crucial functionality.
The third link is special, i don't know if it's of any use, but it seems nice info and the animations are cute.

![3men-small](https://github.com/IlanIwumbwe/Ylva/assets/1109281/20a83429-9b19-4c05-8c25-9dd4a9cf83e3)

**Comment by IlanIwumbwe** [comment]
> I want to share my most recent session with you 
Thank you very much, I'll have a read.
> Here is more nice and valuable info regarding chess engine programming 
Thank you for these, I had a quick skim of the 3rd, it looks really interesting!

**Comment by tissatussa** [comment]
> ..I had a quick skim of the 3rd, it looks really interesting!

i'm not a programmer of any chess engine yet, but i've seen a lot of such coding and i know that smart bit-shift operations are used to create a fastest program .. when i saw that page (which info is much too difficult for me to understand) i had the feeling it might hold some unique approach .. maybe it can help you .. if not, enjoy the animations :-)

**Comment by tissatussa** [comment]
another thing : whenever you want to develop a good time management (which is also very important to create a good engine) i have some info about that too .. many programmers have difficulties with this subject.

**Comment by IlanIwumbwe** [comment]
> another thing : whenever you want to develop a good time management (which is also very important to create a good engine) i have some info about that too .. many programmers have difficulties with this subject.

That would be helpful to learn more about, send over any links you think might be helpful. At the moment, I have iterative deepening on my to-do list which should help in time management.

**Comment by tissatussa** [comment]
> ..send over any links you think might be helpful..

well, i have to find those again, but i will ..

about implementing the UCI protocol : at first you could implement a subset, just the basic commands so Yiva can run in CuteChess : you should certainly use this tool, it's for all OS and the best reference .. people also use Arena but i don't like it and it has issues .. besides that SCID is well known and used often .. but i encounter many engines don't function in SCID, i guess those engine authors didn't properly implement the (UCI) protocol, i don't know, it could also be SCID is buggy somehow .. but if your engine also runs in SCID you're good to go !

i guess you already found the specifications of the UCI protocol .. most famous is that .txt from 2006 but it's not official .. in fact there seems to be no official UCI protocol, but these docs are OK :

[Stockfish wiki : UCI & commands](https://github.com/official-stockfish/Stockfish/wiki/UCI-&-Commands/)
[backscattering chess uci](https://backscattering.de/chess/uci/) : nice layout

**Comment by tissatussa** [comment]
about the time management : i once stumbled upon a remark at https://github.com/xu-shawn/Serendipity/pull/74 :

_Old time management was not tested at a proper time control. This patch replaces the soft time limit algorithm with one from Alexandria._

Serendipity is in Java, Alexandria in C++ !
HTH

**Comment by tissatussa** [comment]
and some time management code from the (strong and small) 4KU engine, also C++ :

https://bityl.co/QQoj
https://bityl.co/QQol
https://bityl.co/QQoo

once the 4KU author(s) wrote about a simple TC formula which i can't find now .. but these code pages probably hold this formula.

**Comment by IlanIwumbwe** [comment]
Thank you for these! I've made some good progress on a subset of UCI protocol. I'm actually trying to figure out time control now so these are particularly helpful

**Comment by tissatussa** [comment]
> ..I'm actually trying to figure out time control now..

As i told you, i remember the 4KU author(s) use(d) a simple formula for this, which works well .. maybe they even invented it .. don't hesitate to contact them for this, you can call my name as reference :-)

![time-management](https://github.com/IlanIwumbwe/Ylva/assets/1109281/33786aa6-5a9a-4b42-bcf0-53cfa94243d5)

Regarding the UCI bonus time functionality : you should know that programs like CuteChess add the bonus time BEFORE every move. So, the engine might have 0 seconds left but still be able to play many moves ..

**Comment by tissatussa** [comment]
Another thing : threads. This can be a hard one .. many engines use just 1 thread, but i also read that many authors use 2 threads to be able to stop or interrupt the calculations procss at any time, eg. when max-time-per-move is reached .. it seems possible to accomplish this with 1 thread, but i don't know much about it and i'm not into C(++), so i can't help you with this one .. it's worth studying this issue though.

**Comment by tissatussa** [comment]
I just asked ChatGPT also about time management. Again it gave a [valuable answer](https://chatgpt.com/share/0c754d9e-690a-4821-920d-bdff5eba0314) immediately !

**Comment by tissatussa** [comment]
And here's another valuable answer from ChatGPT about [CPU Usage in Chess Engines](https://chatgpt.com/share/6e1b2644-bf36-4b2a-950d-49fe4cd0c58c), it might interest you.

You see, as soon as we describe our question accurately, ChatGPT will be a great help !

**Comment by IlanIwumbwe** [comment]
About threads, I am working on implementing one thread that listens to input, and a search thread that runs when "go" is received, then have a queue which engine can keep looking at for new input. However, I was watching [this video](https://www.youtube.com/watch?v=gVGadWuBqEA&list=PLZ1QII7yudbc-Ky058TEaOstZHVbT-2hg&index=70) that uses another method in one thread that keeps peeking at standard input for commands. I quite like this implementation. So I guess either way is possible. 

Thank you for the new links! Much appreciated.

**Comment by tissatussa** [comment]
> ..Thank you for the new links! Much appreciated..

i know ..
and you'll know one can write such once -while it's present- and archive it by posting .. encounter my 4KU Issues .. for me also GitHub allows media embedding !

did you ever use ChatGPT ? like i did ?
i'm into this AI since 7 days or so.

besides the AI and its use, finding and combining existing code modules is key : we can rely on the work of others ! (and name them openly).
To me JSON is a perfect example : this data-structure standard is used by many coders in their modules, to connect everything .. using found C code must be the same thing .. and when a code feels good, go with it !
and keep things simple, clear and and modular.

for many years my email footer is "simple is not always best but best is always simpel", once found .. should i change it to "information understanding knowledge wisdom" ?

AI gives more info soon :-)

**Comment by tissatussa** [comment]
in the README of BrainLearn, a Stockfish version, i find info about "Self Q-learning", using an "experience" file (.exp), which is a plain text data format, resembling the nnue type :

_Boolean, Default: False If activated, the learning algorithm is the Q-learning, optimized for self play. Some GUIs don’t write the experience file in some game’s modes because the uci protocol is differently implemented_

(these english wording is a bit gibberish but) coders extend UCI, we can call it an **unofficial protocol** .. i'm interested in this concept : we can "train" some experience file just by letting (different!) engines play many games and somehow extract data to get a playing style !? I'm thinking of training certain start positions, we can call them "position types", like this one :

![chess-position-type](https://github.com/IlanIwumbwe/Ylva/assets/1109281/35c6dcab-91cf-4bb2-b317-b09edb1d6bbd)

when calculating a move, the engine determines the position type (like those AI complexity rules) and it uses the concerning experience file. I never trained any NN, i only have a notebook, but here i want to use some own simple implementation of this concept.

Few engines i know use such .exp - but i don't know if all are interchangable. The README tells about the CPU time spend for learning while playing : this is time management too !

**Comment by IlanIwumbwe** [comment]
> did you ever use ChatGPT ? like i did ?

I normally use it to learn about new libraries and/or concepts. It seems to be really good at summarizing that information. As you said, knowing how to prompt it well makes it much more useful!

> in the README of BrainLearn, a Stockfish version, i find info about "Self Q-learning", using an "experience" file (.exp)

That's a really interesting idea that I'd like to explore as well. Maybe in later iterations of Ylva as a re-implementation of the evaluation function.

**Comment by tissatussa** [comment]
how's the development going ?
any time spent on it ?

**Comment by IlanIwumbwe** [comment]
Unfortunately, I haven't been able to make time to work on Ylva for the past month as I have been involved in another project, which is going on for another 6 weeks. So probably not much is happening any time soon.

**Comment by IlanIwumbwe** [comment]
- [ ] Currently working on a refactor to improve on Ylva
